"""Private registration numerical implementation."""
from __future__ import annotations
import numpy as np
from scipy.ndimage import zoom
from scipy.spatial import cKDTree
from scipy.spatial.distance import cdist
from ._fields import sanitize_displacement_field
from ._errors import InsufficientLandmarksError
def _gaussian_kernel(moving_points: np.ndarray, beta: float) -> np.ndarray:
    """Compute N×N Gaussian kernel matrix.

    G(i,j) = exp(-||y_i - y_j||² / (2β²))
    """
    dist_sq = cdist(moving_points, moving_points, "sqeuclidean")
    return np.exp(-dist_sq / (2 * beta**2))


def _subsample_points(points: np.ndarray, max_points: int) -> np.ndarray:
    """Farthest-point sampling on a single point cloud.

    Greedy FPS ensures uniform spatial coverage. O(N * max_points).
    """
    n = len(points)
    if n <= max_points:
        return points

    selected = np.zeros(max_points, dtype=np.intp)
    centroid = points.mean(axis=0)
    selected[0] = np.argmin(np.sum((points - centroid) ** 2, axis=1))

    min_dist = np.full(n, np.inf)
    for i in range(1, max_points):
        d = np.sum((points - points[selected[i - 1]]) ** 2, axis=1)
        min_dist = np.minimum(min_dist, d)
        selected[i] = np.argmax(min_dist)

    return points[selected]


def _subsample_with_neighbors(
    points: np.ndarray,
    max_anchors: int = 250,
    k_neighbors: int = 3,
) -> np.ndarray:
    """FPS for spatial anchors, then expand with K nearest neighbors.

    Preserves local cluster structure so CPD can disambiguate
    nearby spots during soft assignment.

    Parameters
    ----------
    points : np.ndarray
        (N, D) point cloud.
    max_anchors : int
        Number of FPS anchor points.
    k_neighbors : int
        Number of nearest neighbors to include per anchor.

    Returns
    -------
    np.ndarray
        (M, D) enriched point cloud where M <= max_anchors * (1 + k_neighbors).
    """
    anchors = _subsample_points(points, max_anchors)
    if len(points) <= max_anchors:
        return anchors  # all points already included

    tree = cKDTree(points)
    k = min(k_neighbors + 1, len(points))  # +1 because nearest is self
    _, indices = tree.query(anchors, k=k)
    all_idx = set(indices.ravel())
    return points[sorted(all_idx)]


def _gather_candidates(
    fixed_sub: np.ndarray,
    moving_all: np.ndarray,
    radius: float = 15.0,
) -> np.ndarray:
    """Gather moving points within radius of subsampled fixed points.

    Ensures every fixed control point has candidate correspondences
    for CPD's EM, without hard pre-matching.

    Parameters
    ----------
    fixed_sub : np.ndarray
        (M, D) subsampled fixed points.
    moving_all : np.ndarray
        (N, D) full moving point cloud.
    radius : float
        Search radius in pixels.

    Returns
    -------
    np.ndarray
        (K, D) moving candidates, K <= N.
    """
    tree = cKDTree(moving_all)
    nearby = tree.query_ball_point(fixed_sub, r=radius)
    idx: set[int] = set()
    for group in nearby:
        idx.update(group)
    return moving_all[sorted(idx)] if idx else moving_all[:0]


def _cpd_e_step(
    reference_points: np.ndarray,
    T: np.ndarray,
    sigma2: float,
    w: float,
    M: int,
    N: int,
    D: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, float]:
    """E-step: compute soft assignment matrix P.

    P(m,n) = probability that fixed point m was generated by moving centroid n.
    Includes uniform outlier component weighted by ``w``.
    """
    dist_sq = cdist(reference_points, T, "sqeuclidean")  # (M, N)
    P = np.exp(-dist_sq / (2 * sigma2))
    c = (2 * np.pi * sigma2) ** (D / 2) * w / (1 - w) * M / N
    denom = P.sum(axis=1, keepdims=True) + c
    P /= denom

    P1 = P.sum(axis=0)  # (N,) responsibility per centroid
    Pt1 = P.sum(axis=1)  # (M,) responsibility per data point
    Np = P1.sum()  # expected number of matches
    return P, P1, Pt1, Np


def _cpd_sigma2(
    reference_points: np.ndarray,
    T: np.ndarray,
    P: np.ndarray,
    P1: np.ndarray,
    Pt1: np.ndarray,
    Np: float,
    D: int,
) -> float:
    """Update variance σ² from current assignments and transformed positions.

    σ² = (1/(Np·D)) · Σ_{m,n} P(m,n) ||x_m - t_n||²
    Computed via trace decomposition to avoid (M, N, D) intermediate.
    """
    PX = P.T @ reference_points  # (N, D)
    val = (
        np.dot(Pt1, np.sum(reference_points**2, axis=1))
        - 2 * np.sum(PX * T)
        + np.dot(P1, np.sum(T**2, axis=1))
    ) / (Np * D)
    return max(val, 1e-10)


def cpd_affine(
    reference_points: np.ndarray,
    moving_points: np.ndarray,
    w: float = 0.1,
    max_iter: int = 100,
    tol: float = 1e-5,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Affine CPD: find affine_matrix, translation such that T(moving_points) = moving_points @ affine_matrix.T + translation.

    Internally normalizes coordinates for numerical stability (anisotropic
    3D data with Z << YX would otherwise make the M-step ill-conditioned).

    Parameters
    ----------
    reference_points : np.ndarray
        (M, D) fixed points.
    moving_points : np.ndarray
        (N, D) moving points (GMM centroids).
    w : float
        Outlier weight in [0, 1). 0 = no outliers.
    max_iter : int
        Maximum EM iterations.
    tol : float
        Relative convergence tolerance on σ².

    Returns
    -------
    tuple[np.ndarray, np.ndarray, np.ndarray]
        ``(transformed_Y, affine_matrix, translation)`` where T(moving_points) = moving_points @ affine_matrix.T + translation
        (in original coordinate space).
    """
    # Per-axis normalization for numerical stability.
    # Global std fails when Z range << YX range (e.g., 32 vs 512),
    # leaving Z ~17x smaller than YX after normalization.
    all_pts = np.concatenate([reference_points, moving_points])
    center = all_pts.mean(axis=0)
    scale = all_pts.std(axis=0)
    scale = np.where(scale < 1e-10, 1.0, scale)  # avoid div-by-zero
    normalized_reference = (reference_points - center) / scale
    normalized_moving = (moving_points - center) / scale

    M, D = normalized_reference.shape
    N = normalized_moving.shape[0]

    Tn = normalized_moving.copy()
    sigma2 = np.sum(cdist(normalized_reference, normalized_moving, "sqeuclidean")) / (D * M * N)

    Bn = np.eye(D)
    tn = np.zeros(D)

    for _ in range(max_iter):
        # E-step
        P, P1, Pt1, Np = _cpd_e_step(normalized_reference, Tn, sigma2, w, M, N, D)

        # M-step: weighted means
        mu_x = normalized_reference.T @ Pt1 / Np  # (D,)
        mu_y = normalized_moving.T @ P1 / Np  # (D,)

        X_hat = normalized_reference - mu_x
        Y_hat = normalized_moving - mu_y

        # affine_matrix = (X_hat^T P Y_hat) @ inv(Y_hat^T diag(P1) Y_hat)
        A = X_hat.T @ P @ Y_hat  # (D, D)
        YPY = Y_hat.T @ (P1[:, None] * Y_hat)  # (D, D)
        Bn = np.linalg.solve(YPY.T, A.T).T

        tn = mu_x - Bn @ mu_y
        Tn = normalized_moving @ Bn.T + tn

        # Update σ²
        sigma2_new = _cpd_sigma2(normalized_reference, Tn, P, P1, Pt1, Np, D)

        if abs(sigma2_new - sigma2) / sigma2 < tol:
            break
        sigma2 = sigma2_new

    # Denormalize with per-axis scale: T(y) = y @ affine_matrix.T + translation in original space.
    # Normalized: y_n = (y - c) @ diag(1/s), T_n = y_n @ Bn.T + tn.
    # Denorm: T = T_n @ diag(s) + c = (y-c) @ diag(1/s) @ Bn.T @ diag(s) + tn@diag(s) + c
    # So: affine_matrix = diag(s) @ Bn @ diag(1/s), translation = c @ (I - affine_matrix.T) + tn * s
    affine_matrix = (scale[:, None] / scale[None, :]) * Bn
    translation = center @ (np.eye(D) - affine_matrix.T) + tn * scale
    T = moving_points @ affine_matrix.T + translation

    return T, affine_matrix, translation


def cpd_nonrigid(
    reference_points: np.ndarray,
    moving_points: np.ndarray,
    beta: float = 3.0,
    lmbda: float = 2.0,
    w: float = 0.1,
    max_iter: int = 150,
    tol: float = 1e-5,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Non-rigid CPD: find weights such that T(moving_points) = moving_points + G @ weights.

    Parameters
    ----------
    reference_points : np.ndarray
        (M, D) fixed points.
    moving_points : np.ndarray
        (N, D) moving points (GMM centroids).
    beta : float
        Gaussian kernel width (pixels). Controls deformation smoothness.
    lmbda : float
        Regularization weight. Higher = smoother, less flexible.
    w : float
        Outlier weight in [0, 1). 0 = no outliers.
    max_iter : int
        Maximum EM iterations.
    tol : float
        Relative convergence tolerance on σ².

    Returns
    -------
    tuple[np.ndarray, np.ndarray, np.ndarray]
        ``(transformed_Y, weights, G)`` where T(moving_points) = moving_points + G @ weights.
    """
    M, D = reference_points.shape
    N = moving_points.shape[0]

    G = _gaussian_kernel(moving_points, max(beta, 1.0))
    T = moving_points.copy()
    sigma2 = np.sum(cdist(reference_points, moving_points, "sqeuclidean")) / (D * M * N)

    for _ in range(max_iter):
        # E-step
        P, P1, Pt1, Np = _cpd_e_step(reference_points, T, sigma2, w, M, N, D)
        PX = P.T @ reference_points  # (N, D)

        # M-step: (G + λσ² diag(1/P1)) weights = diag(1/P1) PX - moving_points
        P1_inv = 1.0 / (P1 + 1e-10)
        A = G + lmbda * sigma2 * np.diag(P1_inv)
        affine_matrix = P1_inv[:, None] * PX - moving_points
        weights = np.linalg.solve(A, affine_matrix)  # (N, D)

        # Update transform
        T = moving_points + G @ weights

        # Update σ²
        sigma2_new = _cpd_sigma2(reference_points, T, P, P1, Pt1, Np, D)

        if abs(sigma2_new - sigma2) / sigma2 < tol:
            break
        sigma2 = sigma2_new

    return T, weights, G


def cpd_displacement_field(
    moving_points: np.ndarray,
    weights: np.ndarray,
    beta: float,
    shape: tuple[int, int, int],
    grid_spacing: int = 16,
    affine_matrix: np.ndarray | None = None,
    translation: np.ndarray | None = None,
    zoom_order: int = 3,
    field_smooth_sigma: float | None = None,
    clamp_sampling_coordinates: bool = True,
) -> np.ndarray:
    """Generate dense backward displacement field from CPD results.

    For each position p in fixed space, computes d(p) such that
    ``moving[p + d(p)] ≈ fixed[p]``.

    Non-rigid backward: ``p_nr = p - K(p, moving_points) @ weights``
    Affine backward (if affine_matrix, translation given): ``p_orig = (p_nr - translation) @ inv(affine_matrix).T``
    Total displacement: ``d = p_orig - p``

    Parameters
    ----------
    moving_points : np.ndarray
        (N, D) kernel centers (affine-corrected moving point positions).
    weights : np.ndarray
        (N, D) CPD non-rigid weight matrix.
    beta : float
        Gaussian kernel width.
    shape : tuple[int, int, int]
        Output field shape (Z, moving_points, reference_points).
    grid_spacing : int
        Coarse grid stride in YX dimensions.
    affine_matrix : np.ndarray, optional
        (D, D) affine matrix from cpd_affine.
    translation : np.ndarray, optional
        (D,) affine translation from cpd_affine.
    zoom_order : int
        Spline order for coarse→full zoom. Default 3 (cubic).
        Use 1 (linear) to eliminate ringing artifacts.
    field_smooth_sigma : float or None
        If set, Gaussian-smooth the displacement field after zoom.

    Returns
    -------
    np.ndarray
        Displacement field with shape (Z, moving_points, reference_points, 3), dtype float32.
    """
    N, D = weights.shape
    beta = max(beta, 1.0)

    # Precompute affine inverse
    has_affine = affine_matrix is not None and translation is not None
    if has_affine:
        B_inv_T = np.linalg.inv(affine_matrix).T

    # Coarse grid
    y_stride = min(grid_spacing, max(1, shape[1] // 4))
    x_stride = min(grid_spacing, max(1, shape[2] // 4))

    zz = np.arange(shape[0])  # every Z slice (Z is typically small)
    yy = np.arange(0, shape[1], y_stride)
    xx = np.arange(0, shape[2], x_stride)

    coarse_shape = (len(zz), len(yy), len(xx))
    coarse_field = np.zeros((*coarse_shape, D), dtype=np.float32)

    # Evaluate Z-slice by Z-slice to limit memory
    two_beta_sq = 2 * beta**2
    for iz, z in enumerate(zz):
        gy, gx = np.meshgrid(yy, xx, indexing="ij")
        gz = np.full_like(gy, z, dtype=np.float64)
        points = np.column_stack(
            [gz.ravel(), gy.ravel(), gx.ravel()]
        )  # (n_pts, 3)

        # Non-rigid backward: p_nr = p - K @ weights
        K = cdist(points, moving_points, "sqeuclidean")
        np.exp(-K / two_beta_sq, out=K)
        p_nr = points - K @ weights

        # Affine backward
        if has_affine:
            p_orig = (p_nr - translation) @ B_inv_T
        else:
            p_orig = p_nr

        disp = (p_orig - points).reshape(len(yy), len(xx), D)
        coarse_field[iz] = disp.astype(np.float32)

    # Zoom each component to full resolution
    zoom_factors = (
        shape[0] / coarse_shape[0],
        shape[1] / coarse_shape[1],
        shape[2] / coarse_shape[2],
    )
    field = np.empty((*shape, D), dtype=np.float32)
    for d in range(D):
        field[..., d] = zoom(coarse_field[..., d], zoom_factors, order=zoom_order)

    # Sanitize: smooth + clamp to prevent OOB and reduce ringing
    field = sanitize_displacement_field(field, clamp=clamp_sampling_coordinates, smooth_sigma=field_smooth_sigma).field

    return field


def cpd_register(
    fixed: np.ndarray,
    moving: np.ndarray,
    detection_threshold: float = 5.0,
    max_control_points: int = 1000,
    beta: float | None = None,
    lmbda: float = 2.0,
    w: float = 0.15,
    affine_first: bool = True,
    grid_spacing: int = 16,
    candidate_radius: float = 15.0,
    k_neighbors: int = 3,
    zoom_order: int = 3,
    field_smooth_sigma: float | None = None,
    clamp_sampling_coordinates: bool = True,
) -> np.ndarray:
    """End-to-end CPD registration.

    1. Detect spots in both volumes
    2. Subsample fixed with FPS anchors + K nearest neighbors
    3. Gather moving candidates within radius of fixed points
    4. Trim fixed points with no nearby moving candidate
    5. Optional affine CPD for global alignment
    6. Non-rigid CPD for local deformation
    7. Generate dense backward displacement field

    Parameters
    ----------
    fixed : np.ndarray
        Fixed (reference) volume, shape (Z, moving_points, reference_points).
    moving : np.ndarray
        Moving volume, shape (Z, moving_points, reference_points).
    detection_threshold : float
        Spot detection sensitivity (lower = more spots).
    max_control_points : int
        Target total fixed point count. FPS anchors are computed as
        ``max_control_points // (1 + k_neighbors)`` so that after
        neighbor expansion the total stays near this value.
    beta : float or None
        Gaussian kernel width (pixels). Controls deformation smoothness.
        If None (default), auto-computed as 5× median nearest-neighbor
        distance in the moving point cloud.
    lmbda : float
        Regularization weight. Higher = smoother.
    w : float
        Expected outlier fraction in [0, 1). Default 0.15 balances
        tolerance to boundary dropout with registration accuracy.
    affine_first : bool
        If True, run affine CPD before non-rigid.
    grid_spacing : int
        Coarse grid stride for field evaluation.
    candidate_radius : float
        Radius (pixels) for gathering moving candidates around each
        fixed point. Ensures true correspondences survive subsampling.
    k_neighbors : int
        Number of nearest neighbors per FPS anchor in the fixed cloud.
        Preserves local cluster structure for CPD soft assignment.
    zoom_order : int
        Spline order for coarse→full zoom (default 3). Use 1 for no ringing.
    field_smooth_sigma : float or None
        Gaussian smoothing sigma for the displacement field after zoom.

    Returns
    -------
    np.ndarray
        Displacement field, shape (Z, moving_points, reference_points, 3) with (dz, dy, dx), float32.

    Raises
    ------
    ValueError
        If fewer than 10 spots detected in either volume, or too few
        moving candidates within the search radius.
    """
    from starfinder.spot_finding import find_spots, NoiseLandmarkConfig
    from starfinder.image import ImageMetadata

    fixed_spots = find_spots(
        fixed, config=NoiseLandmarkConfig(noise_sigma=detection_threshold),
        metadata=ImageMetadata("registration/fixed"), spot_namespace="registration/fixed",
    ).spots[["z", "y", "x"]].to_numpy()
    moving_spots = find_spots(
        moving, config=NoiseLandmarkConfig(noise_sigma=detection_threshold),
        metadata=ImageMetadata("registration/moving"), spot_namespace="registration/moving",
    ).spots[["z", "y", "x"]].to_numpy()

    if len(fixed_spots) < 10 or len(moving_spots) < 10:
        raise InsufficientLandmarksError(
            f"Too few spots for CPD: {len(fixed_spots)} fixed, "
            f"{len(moving_spots)} moving (need >= 10 each)."
        )

    # Correspondence-aware subsampling:
    # FPS anchors + K neighbors for fixed (preserves local clusters),
    # radius-based candidate gathering for moving (preserves true matches).
    max_anchors = max(1, max_control_points // (1 + k_neighbors))
    reference_points = _subsample_with_neighbors(
        fixed_spots, max_anchors=max_anchors, k_neighbors=k_neighbors,
    )
    moving_points = _gather_candidates(reference_points, moving_spots, radius=candidate_radius)

    # Trim fixed points with no moving candidate within radius.
    # Orphaned fixed points (from boundary dropout under large deformations)
    # poison the affine EM with phantom correspondences.
    if len(moving_points) > 0:
        tree_y = cKDTree(moving_points)
        dists, _ = tree_y.query(reference_points, k=1)
        matched = dists <= candidate_radius
        reference_points = reference_points[matched]

    if len(moving_points) < 10:
        raise InsufficientLandmarksError(
            f"Too few moving candidates within {candidate_radius}px "
            f"radius: {len(moving_points)} (need >= 10)."
        )

    # Stage 1: Affine alignment
    affine_matrix, affine_translation = None, None
    if affine_first:
        moving_points, affine_matrix, affine_translation = cpd_affine(reference_points, moving_points, w=w)

    # Auto-compute beta from point cloud density if not specified.
    # 5× median NN distance ensures the Gaussian kernel couples enough
    # neighbors for coherent motion (too-small beta → overfitting).
    if beta is None:
        tree = cKDTree(moving_points)
        k = min(6, len(moving_points))
        dists, _ = tree.query(moving_points, k=k)
        beta = 5.0 * float(np.median(dists[:, 1:])) if k > 1 else 10.0
        beta = max(beta, 1.0)

    # Stage 2: Non-rigid deformation
    _, weights, _ = cpd_nonrigid(reference_points, moving_points, beta=beta, lmbda=lmbda, w=w)

    # Stage 3: Dense field
    return cpd_displacement_field(
        moving_points, weights, beta, fixed.shape,
        grid_spacing=grid_spacing,
        affine_matrix=affine_matrix, translation=affine_translation,
        zoom_order=zoom_order, field_smooth_sigma=field_smooth_sigma,
        clamp_sampling_coordinates=clamp_sampling_coordinates,
    )
