name: starfinder
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aioeasywebdav=2.4.0
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - amply=0.1.5
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - asttokens=2.0.5
  - async-timeout=4.0.3
  - attmap=0.13.2
  - attrs=22.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - bcrypt=4.1.3
  - beautifulsoup4=4.12.3
  - binaryornot=0.4.4
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.3
  - boto3=1.34.136
  - botocore=1.34.136
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2024.6.2
  - certifi=2024.6.2
  - cffi=1.15.1
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.0.0
  - coincbc=2.9.8
  - colorama=0.4.6
  - comm=0.2.1
  - configargparse=1.4
  - connection_pool=0.0.3
  - contourpy=1.0.5
  - cookiecutter=1.7.3
  - cryptography=38.0.4
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2022.7.0
  - datrie=0.8.2
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docutils=0.18.1
  - dpath=2.1.5
  - dropbox=12.0.2
  - eido=0.2.2
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.4.9
  - fftw=3.3.9
  - filechunkio=1.8
  - filelock=3.9.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.4.1
  - fsspec=2022.11.0
  - ftputil=5.1.0
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.30
  - glib=2.69.1
  - google-api-core=2.19.1
  - google-api-python-client=2.135.0
  - google-auth-httplib2=0.2.0
  - google-cloud-core=2.4.1
  - google-cloud-storage=2.17.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.7.0
  - googleapis-common-protos=1.63.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - httplib2=0.22.0
  - humanfriendly=10.0
  - icu=58.2
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.19.3
  - importlib_metadata=7.0.1
  - iniconfig=2.0.0
  - intel-openmp=2021.4.0
  - ipykernel=6.26.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jinja2-time=0.2.0
  - jmespath=1.0.1
  - joblib=1.1.1
  - jpeg=9e
  - jsonschema=4.16.0
  - jupyter_client=8.6.0
  - jupyter_core=5.1.1
  - jupyterlab_pygments=0.2.2
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20240116.2
  - libaec=1.0.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcrc32c=1.1.2
  - libcurl=7.88.1
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc=7.2.0
  - libgcc-ng=12.2.0
  - libgfortran=3.0.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=12.2.0
  - libllvm10=10.0.1
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libpng=1.6.37
  - libpq=12.17
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - locket=1.0.0
  - logmuse=0.2.6
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mdurl=0.1.2
  - mistune=2.0.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.5
  - munkres=1.1.4
  - nbclient=0.8.0
  - nbconvert=7.14.1
  - nbconvert-core=7.14.1
  - nbconvert-pandoc=7.14.1
  - nbformat=5.7.0
  - ncurses=6.3
  - nest-asyncio=1.6.0
  - networkx=2.8.4
  - notebook=6.3.0
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - oauth2client=4.1.3
  - openblas=0.3.4
  - openjpeg=2.4.0
  - openssl=3.3.1
  - packaging=22.0
  - pandas=1.5.2
  - pandoc=3.1.1
  - pandocfilters=1.5.0
  - paramiko=3.4.0
  - parso=0.8.3
  - partd=1.2.0
  - pcre=8.45
  - peppy=0.40.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - plac=1.3.4
  - platformdirs=2.5.2
  - pluggy=1.5.0
  - ply=3.11
  - pooch=1.4.0
  - poyo=0.5.0
  - prettytable=3.10.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - proto-plus=1.23.0
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pulp=2.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pynacl=1.5.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytest=8.2.2
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-irodsclient=2.0.1
  - python-slugify=5.0.2
  - python_abi=3.9
  - pytz=2022.7
  - pyu2f=0.1.5
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.1.2
  - requests=2.28.1
  - reretry=0.11.8
  - rich=13.7.1
  - rise=5.7.1
  - rsa=4.9
  - s3transfer=0.10.2
  - scikit-image=0.19.3
  - scikit-learn=1.2.0
  - scipy=1.10.0
  - seaborn=0.12.2
  - send2trash=1.8.2
  - setuptools=67.4.0
  - sip=6.6.2
  - six=1.16.0
  - slacker=0.14.0
  - smart_open=5.2.1
  - smmap=4.0.0
  - snakemake=7.32.4
  - snakemake-minimal=7.32.4
  - snappy=1.1.9
  - soupsieve=2.5
  - sqlite=3.40.1
  - stack_data=0.2.0
  - stone=3.3.2
  - stopit=1.1.2
  - tabulate=0.8.10
  - terminado=0.17.1
  - text-unidecode=1.3
  - threadpoolctl=2.2.0
  - throttler=1.2.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - toposort=1.10
  - tornado=6.2
  - traitlets=5.7.1
  - typing_extensions=4.11.0
  - tzdata=2022g
  - ubiquerg=0.8.0
  - unidecode=1.2.0
  - uritemplate=4.1.1
  - urllib3=1.26.14
  - veracitools=0.1.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.38.4
  - wrapt=1.14.1
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - yte=1.5.1
  - zeromq=4.3.5
  - zfp=0.5.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - absl-py==1.4.0
    - anndata==0.9.1
    - annotated-types==0.6.0
    - astunparse==1.6.3
    - cachetools==5.3.0
    - cairocffi==1.6.1
    - csbdeep==0.7.3
    - dacite==1.8.1
    - et-xmlfile==1.1.0
    - fastdist==1.1.5
    - flatbuffers==23.3.3
    - gast==0.4.0
    - google-auth==2.17.3
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - grpcio==1.53.0
    - h5py==3.8.0
    - htmlmin==0.1.12
    - igraph==0.11.3
    - imagehash==4.3.1
    - importlib-metadata==6.4.0
    - ipywidgets==8.1.1
    - jax==0.4.8
    - jupyterlab-widgets==3.0.9
    - keras==2.12.0
    - leidenalg==0.10.2
    - libclang==16.0.0
    - llvmlite==0.39.1
    - lxml==4.9.3
    - markdown==3.4.3
    - ml-dtypes==0.1.0
    - multimethod==1.10
    - natsort==8.3.1
    - numba==0.56.4
    - oauthlib==3.2.2
    - opencv-python==4.7.0.72
    - openpyxl==3.1.2
    - opt-einsum==3.3.0
    - p2j==1.3.2
    - pandas-profiling==3.6.6
    - parse==1.20.2
    - patsy==0.5.3
    - phik==0.12.3
    - plotly==5.18.0
    - protobuf==4.22.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==2.4.2
    - pydantic-core==2.10.1
    - pynndescent==0.5.8
    - requests-oauthlib==1.3.1
    - scanpy==1.9.3
    - session-info==1.0.0
    - split-image==2.0.1
    - stardist==0.8.3
    - statsmodels==0.13.5
    - stdlib-list==0.8.0
    - tangled-up-in-unicode==0.2.0
    - tenacity==8.2.3
    - tensorboard==2.12.2
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.12.0
    - tensorflow-estimator==2.12.0
    - tensorflow-io-gcs-filesystem==0.32.0
    - termcolor==2.2.0
    - texttable==1.7.0
    - tifffile==2023.4.12
    - tqdm==4.65.0
    - typeguard==4.1.5
    - umap-learn==0.5.3
    - visions==0.7.5
    - werkzeug==2.2.3
    - widgetsnbextension==4.0.9
    - wordcloud==1.9.2
    - ydata-profiling==4.6.1
    - zipp==3.15.0
