name: starfinder
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.3.1
  - amply=0.1.6
  - anndata=0.10.9
  - anyio=4.2.0
  - aom=3.9.1
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - argparse-dataclass=2.0.0
  - arpack=3.9.1
  - array-api-compat=1.8
  - asciitree=0.3.3
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attmap=0.13.2
  - attrs=24.2.0
  - aws-c-auth=0.7.26
  - aws-c-cal=0.7.4
  - aws-c-common=0.9.27
  - aws-c-compression=0.2.19
  - aws-c-event-stream=0.4.3
  - aws-c-http=0.8.8
  - aws-c-io=0.14.18
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.4
  - aws-c-sdkutils=0.1.19
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.28.0
  - aws-sdk-cpp=1.11.379
  - azure-core-cpp=1.13.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.12.0
  - azure-storage-common-cpp=12.7.0
  - azure-storage-files-datalake-cpp=12.11.0
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - bleach=4.1.0
  - blosc=1.21.6
  - bokeh=3.5.2
  - branca=0.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.33.1
  - c-blosc2=2.15.1
  - ca-certificates=2024.7.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2024.7.4
  - cffi=1.17.0
  - cfitsio=4.4.1
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - coin-or-cbc=2.10.12
  - coin-or-cgl=0.60.9
  - coin-or-clp=1.17.10
  - coin-or-osi=0.108.11
  - coin-or-utils=2.11.12
  - coincbc=2.10.12
  - colorama=0.4.6
  - colorcet=3.1.0
  - comm=0.2.1
  - conda-inject=1.3.2
  - configargparse=1.7
  - connection_pool=0.0.3
  - contourpy=1.2.1
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask=2024.8.1
  - dask-core=2024.8.1
  - dask-expr=1.1.11
  - dask-image=2024.5.3
  - datashader=0.16.3
  - datrie=0.8.2
  - dav1d=1.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2024.8.1
  - docrep=0.3.2
  - docutils=0.21.2
  - dpath=2.2.0
  - eido=0.2.2
  - exceptiongroup=1.2.2
  - executing=0.8.3
  - expat=2.6.2
  - fasteners=0.17.3
  - filelock=3.15.4
  - fmt=11.0.2
  - folium=0.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - freetype=2.12.1
  - freexl=2.0.0
  - frozenlist=1.4.1
  - fsspec=2023.6.0
  - gdal=3.9.2
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geos=3.12.2
  - geotiff=1.7.3
  - get-annotations=0.1.2
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glog=0.7.1
  - glpk=5.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - h2=4.1.0
  - h5py=3.11.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - humanfriendly=10.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.8
  - igraph=0.10.13
  - imagecodecs=2024.6.1
  - imageio=2.35.1
  - immutables=0.20
  - importlib-metadata=8.4.0
  - importlib_metadata=8.4.0
  - importlib_resources=6.4.4
  - inflect=7.3.1
  - iniconfig=2.0.0
  - ipykernel=6.28.0
  - ipython=8.25.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json-c=0.17
  - json5=0.9.6
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jxrlib=1.1
  - kealib=1.5.3
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - legacy-api-wrap=1.4
  - leidenalg=0.10.2
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.7.4
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libavif16=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.9.1
  - libdeflate=1.21
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgdal=3.9.2
  - libgdal-core=3.9.2
  - libgdal-fits=3.9.2
  - libgdal-grib=3.9.2
  - libgdal-hdf4=3.9.2
  - libgdal-hdf5=3.9.2
  - libgdal-jp2openjpeg=3.9.2
  - libgdal-kea=3.9.2
  - libgdal-netcdf=3.9.2
  - libgdal-pdf=3.9.2
  - libgdal-pg=3.9.2
  - libgdal-postgisraster=3.9.2
  - libgdal-tiledb=3.9.2
  - libgdal-xls=3.9.2
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.3
  - libgomp=14.1.0
  - libgoogle-cloud=2.28.0
  - libgoogle-cloud-storage=2.28.0
  - libgrpc=1.62.2
  - libhwloc=2.11.1
  - libhwy=1.1.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libjxl=0.10.3
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libleidenalg=0.11.1
  - libllvm14=14.0.6
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libparquet=17.0.0
  - libpng=1.6.43
  - libpq=16.4
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialite=5.1.0
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libthrift=0.20.0
  - libtiff=4.6.0
  - libtorch=2.4.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.48.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzip=1.10.1
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvmlite=0.43.0
  - locket=1.0.0
  - logmuse=0.2.6
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.8.0
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - matplotlib-scalebar=0.8.1
  - mdurl=0.1.2
  - minizip=4.0.7
  - mistune=2.0.4
  - more-itertools=10.4.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.0.8
  - multidict=6.0.5
  - multipledispatch=0.6.0
  - multiscale-spatial-image=1.0.0
  - munkres=1.1.4
  - natsort=8.4.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nomkl=1.0
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.103
  - numba=0.60.0
  - numcodecs=0.13.0
  - numpy=1.26.4
  - ome-zarr=0.9.0
  - omnipath=1.0.8
  - openjpeg=2.5.2
  - openssl=3.3.1
  - orc=2.0.2
  - overrides=7.4.0
  - packaging=24.1
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - param=2.1.1
  - parse=1.19.1
  - parso=0.8.3
  - partd=1.4.2
  - patsy=0.5.6
  - pcre2=10.44
  - peppy=0.40.5
  - pexpect=4.8.0
  - pillow=10.4.0
  - pims=0.7
  - pip=24.2
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - plac=1.4.3
  - platformdirs=4.2.2
  - pluggy=1.5.0
  - pooch=1.8.2
  - poppler=24.08.0
  - poppler-data=0.4.12
  - postgresql=16.4
  - proj=9.4.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulp=2.8.0
  - pure_eval=0.2.2
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pyarrow-hotfix=0.6
  - pycparser=2.22
  - pyct=0.5.0
  - pygments=2.18.0
  - pynndescent=0.5.13
  - pyogrio=0.9.0
  - pyparsing=3.1.4
  - pyproj=3.6.1
  - pysocks=1.7.1
  - pytest=8.3.2
  - python=3.12.5
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-igraph=0.11.6
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytorch=2.4.0
  - pytz=2024.1
  - pywavelets=1.7.0
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - qhull=2020.2
  - rav1e=0.6.6
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - reretry=0.11.8
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.1
  - rpds-py=0.20.0
  - s2n=1.5.1
  - scanpy=1.10.2
  - scikit-image=0.24.0
  - scikit-learn=1.5.1
  - scipy=1.14.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.2
  - session-info=1.0.0
  - setuptools=72.2.0
  - shapely=2.0.6
  - six=1.16.0
  - slack-sdk=3.31.0
  - slack_sdk=3.31.0
  - sleef=3.6.1
  - slicerator=1.1.0
  - smart_open=7.0.4
  - smmap=5.0.0
  - snakemake=8.18.2
  - snakemake-interface-common=1.17.3
  - snakemake-interface-executor-plugins=9.2.0
  - snakemake-interface-report-plugins=1.0.0
  - snakemake-interface-storage-plugins=3.3.0
  - snakemake-minimal=8.18.2
  - snappy=1.2.1
  - sniffio=1.3.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - spatial-image=1.0.0
  - spatialdata=0.2.2
  - spdlog=1.14.1
  - sqlite=3.46.0
  - squidpy=1.5.0
  - stack_data=0.2.0
  - statsmodels=0.14.2
  - stdlib-list=0.10.0
  - stopit=1.1.2
  - svt-av1=2.2.1
  - sympy=1.13.2
  - tabulate=0.9.0
  - tbb=2021.12.0
  - tblib=3.0.0
  - terminado=0.17.1
  - texttable=1.7.0
  - threadpoolctl=3.5.0
  - throttler=1.2.2
  - tifffile=2024.8.28
  - tiledb=2.25.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - tomli=2.0.1
  - toolz=0.12.1
  - toposort=1.10
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typeguard=4.3.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzcode=2024a
  - tzdata=2024a
  - ubiquerg=0.8.0
  - umap-learn=0.5.6
  - uriparser=0.9.8
  - urllib3=2.2.2
  - validators=0.33.0
  - veracitools=0.1.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - wrapt=1.16.0
  - xarray=2023.12.0
  - xarray-dataclasses=1.7.0
  - xarray-datatree=0.0.14
  - xarray-schema=0.0.3
  - xarray-spatial=0.4.0
  - xerces-c=3.2.5
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2024.6.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - yte=1.5.4
  - zarr=2.18.2
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.20.1
  - zlib=1.3.1
  - zlib-ng=2.2.1
  - zstandard=0.23.0
  - zstd=1.5.6
